Vagrant.configure("2") do |config|

  config.ssh.forward_x11 = true

  config.vm.define :opus do |opus|
    opus.vm.hostname = "opus"
    opus.vm.box = "ubuntu/trusty64"
    opus.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160107.1.0/providers/virtualbox.box"

    opus.vm.provision "shell" do |s|
      s.privileged = false
      s.path = "opus-initialize.sh"
    end

    opus.vm.network "private_network", ip: "192.168.1.2" , netmask: "255.255.255.0"
  end
end
