#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 -a "$#" -ne 3 ]
then
        echo "Usage: "$0" <Stage Path> [GCC_MACRO] [--static]"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <unistd.h>
int main() {char *argv[] = {"`realpath tmp`",NULL}; 
char *envr[] = {NULL};
int rn = 0;
#ifdef PROGRAM 
rn=execve(argv[0],argv,envr);
#endif
return (rn==-1);
}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $3 $TMPFILE

echo "#!/bin/bash" > tmp
chmod 0755 tmp

rm "$TMPFILE"
chown 1000:1000 *
