#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 ]
then
	echo "Usage: "$0" <Stage Path> [--static]"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <unistd.h>
void main() {char *argv[] = {"./tmp",0); execve(argv[0],&argv[0],0);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $TMPFILE

touch tmp
chmod 0755 tmp

rm "$TMPFILE"
chown 1000:1000 *
