#!/bin/bash

if [ "$#" -le 1 ]
then
    	echo "Usage: "$0" <Stage Path> [GCC_MACRO]"
        echo "Sample: "$0" ./stage -DPROGRAM --static"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#define _GNU_SOURCE
#include <unistd.h>
#include <sys/types.h>
int main() {int rn=0;
gid_t gid = getgid();
#ifdef PROGRAM
rn=setresgid(gid,gid,gid);
#endif
return (rn==-1);}
EOF
)
TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2} $TMPFILE

rm "$TMPFILE"
chown 1000:1000 *
