#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 ]
then
	echo "Usage: "$0" <Stage Path> [--static]"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <unistd.h>
#include <sys/stat.h>
void main() {mknodat(open(".",O_DIRECTORY),"newtest.txt", S_IFREG | S_IRWXU | S_IRGRP | S_IROTH, 0);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $TMPFILE

rm "$TMPFILE"
