#!/bin/bash

if [ "$#" -le 1 ]
then
    	echo "Usage: "$0" <Stage Path> [GCC_MACRO]"
        echo "Sample: "$0" ./stage -DPROGRAM --static"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include<stdio.h>
#include<fcntl.h>
#include<unistd.h>
int main() {int d=open("`realpath $1`",O_DIRECTORY); int rn=0;
#ifdef PROGRAM
rn=renameat(d,"test.txt",d, "renameat-test.txt");
#endif
close(d);
return (rn==-1);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2} $TMPFILE

touch test.txt
echo "TEST" > test.txt

rm "$TMPFILE"
chown 1000:1000 *

