#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 -a "$#" -ne 3 ]
then
	echo "Usage: "$0" <Stage Path> [GCC_MACRO] [--static]"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <sched.h>
static int childFunc(void *args) {}
int main() {char* tmp = malloc(1024*1024); int id=0;
#ifdef PROGRAM
id=clone(childFunc,tmp+1024*1024,CLONE_PARENT,NULL);
#endif
free(tmp);
return (id==-1);
}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $3 $TMPFILE

rm "$TMPFILE"
chown 1000:1000 *
