#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 ]
then
	echo "Usage: "$0" <Stage Path> [--static]"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <sched.h>
static int childFunc(void *args) {}
void main() {char* tmp = malloc(1024*1024); clone(childFunc,tmp+1024*1024,CLONE_PARENT,NULL);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $TMPFILE

rm "$TMPFILE"
chown vagrant:vagrant *
