#!/bin/bash

if [ "$#" -le 1 ]
then
    	echo "Usage: "$0" <Stage Path> [GCC_MACRO]"
        echo "Sample: "$0" ./stage -DPROGRAM --static"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include<fcntl.h>
#include<unistd.h>
int main() {
int id=0;
#ifdef PROGRAM
id+=creat("`realpath $1`/newtest.txt",S_IRWXU|S_IRWXG);
id+=unlink("`realpath $1`/newtest.txt");
#endif
return (id==-1);
}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2} $TMPFILE

rm "$TMPFILE"
chown 1000:1000 *
