#!/bin/bash

if [ "$#" -le 1 ]
then
    	echo "Usage: "$0" <Stage Path> [GCC_MACRO]"
        echo "Sample: "$0" ./stage -DPROGRAM --static"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <unistd.h>
int main() {int rn=0;
#ifdef PROGRAM
rn=chown("`realpath $1`/test.txt", 1000, 1000);
#endif
return (rn==-1);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2} $TMPFILE

touch test.txt

rm "$TMPFILE"
sudo chown root:root *
sudo chmod u+s test
