#!/bin/bash

if [ "$#" -le 1 ]
then 
        echo "Usage: "$0" <Stage Path> [GCC_MACRO]"
	echo "Sample: "$0" ./stage -DREAD=3 -DWRITE=4 -DPROGRAM --static"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <fcntl.h>
#include <unistd.h>
int main() {int id=open("`realpath $1`/test.txt", O_RDWR); int rn=0; char buf[1]; int i;
#ifdef READ
for (i=0;i<READ;i++) {
#ifdef PROGRAM
rn=read(id, buf, 1);
printf("T1");
#endif
if (rn==-1) break;
}
#endif
#ifdef WRITE
for (i=0;i<WRITE;i++) {
#ifdef PROGRAM
rn=write(id, "TEST", 1);
printf("T2");
#endif
if (rn==-1) break;
}
#endif
close(id);
return (rn==-1);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2} $TMPFILE

touch test.txt
echo "TEST" > test.txt

rm "$TMPFILE"
chown 1000:1000 *
