#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 ]
then
	echo "Usage: "$0" <Stage Path> [--static]"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <unistd.h>
#include <fcntl.h>
void main() {symlinkat("test.txt",open(".",O_DIRECTORY),"symlinkat-test.txt");}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $TMPFILE

touch test.txt
echo "TEST" > test.txt

rm "$TMPFILE"
chown 1000:1000 *
