#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 -a "$#" -ne 3 ]
then
        echo "Usage: "$0" <Stage Path> [GCC_MACRO] [--static]"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include<fcntl.h>
#include<unistd.h>
void main() {
#ifdef PROGRAM
int f = creat("`realpath newtest.txt`",S_IRWXU|S_IRWXG);
#endif
close(f);
}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $3 $TMPFILE

rm "$TMPFILE"
chown 1000:1000 *
