#!/bin/bash

if [ "$#" -ne 1 ]
then
	echo "Usage: "$0" <Stage Path>"
	exit 1
fi

cd "$1"
pwd
#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
void main() {}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc --static -o test "$TMPFILE"

rm "$TMPFILE"
