#!/bin/bash

if [ "$#" -le 1 ]
then
	echo "Usage: "$0" <Stage Path> [GCC_MARCO]"
	echo "Sample: "$0" ./stage -DPROGRAM --static"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <sys/stat.h>
int main() {
int rn=0;
#ifdef PROGRAM
rn=chmod("`realpath $1`/test.txt", S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH); 
#endif
return (rn==-1);
}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2} $TMPFILE

touch test.txt
chmod 0600 test.txt

rm "$TMPFILE"
chown 1000:1000 *
