#!/bin/bash

if [ "$#" -le 1 ]
then
    	echo "Usage: "$0" <Stage Path> [GCC_MACRO]"
        echo "Sample: "$0" ./stage -DPROGRAM --static"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#define _GNU_SOURCE
#include <fcntl.h>
#include <unistd.h>
#include<stdio.h>
#include <unistd.h>

int main() {int fd[2],fd2[2]; int rn=0;
char buf[4];
if (pipe(fd) == -1) return 1;
if (pipe(fd2) == -1) return 1;
write(fd[1],"a",1);
#ifdef PROGRAM
rn = tee(fd[0], fd2[1], 1, 0);
#endif
return (rn==-1);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test ${*:2}  $TMPFILE

rm "$TMPFILE"
chown 1000:1000 *
chmod a+x test
