#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 ]
then
	echo "Usage: "$0" <Stage Path> [--static]"
	exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <sys/stat.h>
void main() {chmod("test.txt", S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $TMPFILE

touch test.txt
chmod 0600 test.txt

rm "$TMPFILE"
chown 1000:1000 *
