Vagrant.configure("2") do |config|

  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.define :spade do |spade|
    spade.vm.hostname = "spade"
    spade.vm.box = "ubuntu/trusty64"

    spade.vm.provision "shell" do |s|
      s.privileged = false
      s.path = "spade-audit-initialize.sh"
    end

    spade.vm.network "private_network", ip: "192.168.1.2" , netmask: "255.255.255.0"
  end
end
