#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 -a "$#" -ne 3 ]
then 
        echo "Usage: "$0" <Stage Path> [GCC_MACRO] [--static]"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#include <unistd.h>
int main() {int rn=0;
#ifdef PROGRAM
rn=unlink("`realpath link-test.txt`");
#endif
return (rn==-1);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o test $2 $3 $TMPFILE

touch test.txt
echo "TEST" > test.txt
link test.txt link-test.txt

rm "$TMPFILE"
chown 1000:1000 *
