#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 -a "$#" -ne 3 ]
then 
        echo "Usage: "$0" <Stage Path> [GCC_MACRO] [--static]"
        exit 1
fi

cd "$1"

#Clean directory
ls | grep -v 'prepare' | xargs rm -f

#Prepare Benchmark Program
CODE=$(cat <<EOF
#define _GNU_SOURCE
#include <fcntl.h>
#include <unistd.h>
int main() {int rn=0;
#ifdef PROGRAM
rn=tee(STDIN_FILENO,STDOUT_FILENO,1,0);
#endif
return (rn==-1);}
EOF
)

TMPFILE=$(mktemp -t tmp.XXXXXX.c)
echo "$CODE">$TMPFILE

gcc -o tee $2 $3 $TMPFILE
echo -e "#!/bin/bash\necho A | `realpath tee` | echo " > test

rm "$TMPFILE"
chown 1000:1000 *
chmod a+x test
